### ISSUE TITLE
Error when importing.

### ISSUE THREAD

**Issue by LandonAndEmma** [hayden0729/berrybush#9] opened 2024-06-27 17:46 UTC
Here's my file and error. I'm using Blender 3.3 LTS
[error.txt](https://github.com/user-attachments/files/16019014/error.txt)
[https://www.mediafire.com/file/rymj1v549v99l0y/Tsuruya.7z/file](url)

**Comment by hayden0729** [comment] 2024-06-29 14:48
Hey, thanks for the report. This looks like a duplicate of #8, so you can follow the steps listed there to troubleshoot. The error message tells you which texture is problematic ('ToonTex_02' of material 'body_up_000'), so you'll have to change that texture's settings in BrawlCrate. If there are any other textures with issues, it'll tell you after you've fixed that one.

**Closed** 2024-07-12 10:47 UTC

**Comment by LandonAndEmma** [comment] 2024-07-13 19:45
Okay thank you
